<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Encore un Blog ?! #nonMaisAllo</title>

    <!-- Feuilles de style externes -->
    <link rel="stylesheet" href="css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">

    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="css/blog-main.css">
    <link rel="stylesheet" href="css/blog-theme.css">
    <link rel="stylesheet" href="css/ui-button.css">
    <link rel="stylesheet" href="css/ui-form.css">
</head>
<body>
        <!-- En-tête commune de l'application -->
    <header class="blog-header">
        <h1><a href="index.php"><i class="fa fa-microphone"></i> Encore un Blog ?! #nonMaisAllo</a></h1>
        <nav>

             <!-- Si connecter  -->

            <?php if(!empty($_SESSION)) {?>
            <a href="deco.php"><i class="fa fa-cogs"></i> Deconnexion</a>
            <a href="admin.php"><i class="fa fa-cogs"></i> Gestion de Post</a>
            <?php };?>
                        <!-- si tu es super admin  -->
            <?php if((!empty($_SESSION)) && ($_SESSION['role'] == 'admin')) {?>
            <a href="bigAdmin.php"><i class="fa fa-cogs"></i> Adiministration</a>
            <?php };?>

            <!-- si tu es deconnecter -->
            <?php if(empty($_SESSION)) {?>
            <a href="login.php"><i class="fa fa-cogs"></i> Login</a>
            <a href="register.php"><i class="fa fa-cogs"></i> Register</a>
            <?php };?>

            <a href="index.php"><i class="fa fa-home"></i> Accueil</a>

        </nav>
    </header>
      <main>
        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <?php include $template.'.phtml' ?>
    </main>

    <!-- Pied de page commun de l'application -->
    <footer class="blog-footer">
        <small>Le blog des élèves de la 3W Academy</small>
    </footer>
</body>
</html>