<h2>Connexion</h2>
<form class="generic-form" action="login.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Identifiants</legend>
        <ul>
            <li>
                <?php if ($error == true ) { echo $message; } ?>
            </li>
			<li>
				<label for="mail">Adresse mail :</label>
				<input type="mail" placeholder="Adresse mail" id="mail" name="email" required>
			</li>
            <li>
				<label for="psw">Mot de passe :</label>
				<input type="password" placeholder="Mot de passe" id="psw" name="psw" required>
			</li>
			<li>
                <button class="button button-primary" type="submit">Connexion</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>