<h2><i class="fa fa-file-text-o"></i> Article</h2>

<!-- Article du blog -->
<section class="post">
    <h3><?=htmlspecialchars($postDetail['post_title'])?></h3>
    <article><?=htmlspecialchars($postDetail['post_contents'])?></article>
    
    <small>Rédigé par <?= $postDetail['author_firstName']?> <?= $postDetail['author_lastName']?>, le <?=$postDetail['post_dateCreation']?></small>

</section>

<hr>

<!-- Liste des commentaires de l'article du blog -->
<ul class="comment-list">
    <?php foreach ($commentDetail as $key => $value ) {?>
            <li class="comment">
            <h4><i class="fa fa-comment"></i> <?=htmlspecialchars($value['comment_pseudo'])?></h4>
            <article><?=htmlspecialchars($value['comment_content'])?></article>
        </li>
    <?php } ?>
    </ul>


<hr>

<!-- Formulaire de saisie d'un nouveau commentaire pour cet article -->
<form class="generic-form" action="post.php?id=<?=$_GET['id']?>" method="POST">

    <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le commentaire -->
    <input type="hidden" name="postId" value="<?=$_GET['id']?>">

    <fieldset>
        <legend><i class="fa fa-comment-o"></i> Nouveau commentaire</legend>
        <ul>
            <li>
                <label for="nickName">Pseudo :</label>
                <input type="text" id="nickName" name="nickName">
            </li>
            <li>
                <label class="textarea" for="contents">Commentaire :</label>
                <textarea id="contents" name="contents" rows="5"></textarea>
            </li>
            <li>
                <button class="button button-primary" type="submit">Ajouter</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>   