<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Loterie 3WAcademy</title>
</head>
<body>
        <h1>Loterie 3WAcademy</h1>

        <p>Le résultat du tirage de la loterie 3WAcademy est :
            <?= $write_tab ?></p>
</body>
</html>