<!--methode 1-->
    <?/*php include 'header.phtml' */?>
	<form action="recap.php" method="POST">
        	<input type="text" placeholder="Nom" name="lastname"/>
        	<input type="text" placeholder="Prénom" name="firstname"/>
            <input type="text" placeholder="Email" name="email"/>
            <input type="text" placeholder="Adresse" name="address"/>
            <input type="text" placeholder="Ville" name="city"/>
            <input type="submit" value="Envoyer"/>
        </form>
	<?/*php include 'footer.phtml' */?>

</body>
</html>